### ISSUE TITLE
SlideWindow2

### ISSUE THREAD

**Issue by mdrmdrmdr** [plashenkov/powerline#1]
Hi Yury,

I'm very sorry to write here regarding a non "powerline" topic, but I did not find any alternative solution to contact you.

A long time ago you wrote **SlideWindow2**, a Javascript picture viewer. I'm still using it since it perfectly fits my needs. Unfortunately I only have the compacted "min" version and lost the full one. I'd like to do same changes and therefore the full version or "SlideWindow2.zip" would be great. Any chance that you still have it somewhere? Thanks a lot!

**Comment by plashenkov** [comment]
Hi @mdrmdrmdr! Wow. Unfortunately I doubt I have the full version somewhere. Please could you send the compacted version to me? I'll look into it and maybe I'll be able to restore the full version. My email: my nick here [at] gmail.com

**Comment by mdrmdrmdr** [comment]
Just sent a mail... :-)

**Comment by plashenkov** [comment]
Got it! Let's close this and continue in mail.
